name: Deploy K8s Dashboard to Core Pages

on:
  schedule:
    - cron: '0 3 * * *' # Corre 1 vez al día a las 3:00 AM UTC (Madrugada)
  workflow_dispatch: # Permite correrlo manualmente desde GitHub si tienes afán


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código base
        uses: actions/checkout@v4
      
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Ejecutar Extractor Matemático (Limpieza IQR)
        run: node docs/procesador.js
        
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5
        
      - name: Subir Documentos Generados (Artifact)
        uses: actions/upload-pages-artifact@v3
        with:
          # Sube explícitamente la carpeta pre-computada al Host
          path: './docs'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Desplegar hacia GitHub Pages Serverless
        id: deployment
        uses: actions/deploy-pages@v4
